paths:
  data: test-data.log
  data_dir: /data
  tasks_dir: /tasks
  models_dir: /models
  policies_dir: /policies
  diffs_dir: /diffs
  plots_dir: /plots
settings:
  max_attributes: 20
  max_buffer: 50
  window_size: 10
  g: 1
  k: 8
  c: 1
  decay: 0.7
  preferred_attributes: {}
  always_allow: |
  always_deny: |
