paths:
  data: synth-heart13.log
  # data: monitoring-grafana-quiz.log
  # allow_list: synth-heart11-allow.log
  # block_list: synth-heart11-block.log
  data_dir: /data
  tasks_dir: /tasks
  models_dir: /models
  policies_dir: /policies
  diffs_dir: /diffs
  plots_dir: /plots
settings:
  # max_attributes: 20
  # window_size: 50
  # generalisation: 1
  # decay: 0.7
  # drop_threshold: 0.1
  # warm_up: 30
  # time_penalty: 0.1

  # max_attributes: 25
  # window_size: 50
  # generalisation: 1
  # decay: 0.85
  # drop_threshold: 0.1
  # warm_up: 30
  # time_penalty: 0.006

  # max_attributes: 25
  # window_size: 50
  # generalisation: 30
  # # decay: 0.75
  # # drop_threshold: 0.1
  # decay: 0.9
  # drop_threshold: 0.1
  # warm_up: 30
  # # calibrate_interval: 200
  # calibrate_interval: 200

  max_attributes: 25
  max_requests: 1000
  window_size: 50
  generalisation: 1
  decay: 0.9
  calibrate_interval: 200
