paths:
  data: synth-heart11.log
  # allow_list: synth-heart11-allow.log
  # block_list: synth-heart11-block.log
  data_dir: /data
  tasks_dir: /tasks
  models_dir: /models
  policies_dir: /policies
  diffs_dir: /diffs
  plots_dir: /plots
settings:
  # max_attributes: 20
  # window_size: 100
  # relearn_threshold: 1.5
  # generalisation: 1
  # decay: 0.5
  # drop_threshold: 0.05
  # warm_up: 20

  # max_attributes: 20
  # window_size: 100
  # relearn_threshold: 1.5
  # generalisation: 1
  # decay: 0.5
  # drop_threshold: 0.05
  # warm_up: 20

  max_attributes: 20
  window_size: 50
  relearn_threshold: 1.5
  generalisation: 1
  decay: 0.7
  drop_threshold: 0.1
  warm_up: 30
