paths:
  data: flexibility.json
  data_dir: /data
  tasks_dir: /tasks
  models_dir: /models
  policies_dir: /policies
  diffs_dir: /diffs
  plots_dir: /plots
settings:
  max_attributes: 30
  max_buffer: 100
  window_size: 1
  g: 3
  k: 2
  c: 1
  decay: 0.9
  preferred_attributes:
    - "request__method(M)"
    - "request__body(B)"
    - "parsed_path(I, P)"
  always_allow: |

  always_deny: |
