paths:
  # data: lacework/agent/2021-05-26/2021-05-26-13-00/pod_summary.json.gz
  # data: lacework2/lacework/agent/2021-05-27/2021-05-27-13-00/pod_summary.json.gz
  # data: synth-heart13.log

  # data: lacework2/lacework/agent/2021-05-27
  # data_type: pod_summary.json.gz





  # data: lacework2/lacework/test-set.json
  # data: lacework2/lacework/test-set-final.json








  data: lacework2/lacework/test-set4.json
  # data: lacework2/lacework/test-distribution-s-small.json
  # data: lacework2/lacework/test-distribution-s-large.json




  # data: synth-heart13.log

  # data: lacework2/lacework/test-distribution-s3.json
  # data: lacework2/lacework/test-distribution-s2.json
  # data: lacework2/lacework/test-set3.json





  # data: synth-heart13.log
  # data: lacework/agent/2021-05-27/2021-05-27-00-00/dns_query.json.gz
  # data: lacework/agent/2021-05-27/2021-05-27-00-00/process_summary.json.gz
  # data: lacework2/lacework/agent/2021-05-27
  # data_type: pod_summary.json.gz
  # data: lacework/agent/2021-05-27/2021-05-27-00-00/connections.json.gz
  # data: lacework/agent/2021-05-27/2021-05-27-00-00/container_summary.json.gz
  # data: lacework/agent/2021-05-27/2021-05-27-00-00/machine_details.json.gz
  # data: lacework/agent/2021-05-27/2021-05-27-00-00/all_files.json.gz
  # data: lacework/processed/change_files.json
  # data: monitoring-grafana-quiz.log
  # allow_list: synth-heart11-allow.log
  # block_list: synth-heart11-block.log
  data_dir: /data
  tasks_dir: /tasks
  models_dir: /models
  policies_dir: /policies
  diffs_dir: /diffs
  plots_dir: /plots
settings:
  # max_attributes: 20
  # window_size: 50
  # generalisation: 1
  # decay: 0.7
  # drop_threshold: 0.1
  # warm_up: 30
  # time_penalty: 0.1

  # max_attributes: 25
  # window_size: 50
  # generalisation: 1
  # decay: 0.85
  # drop_threshold: 0.1
  # warm_up: 30
  # time_penalty: 0.006

  # max_attributes: 25
  # window_size: 50
  # generalisation: 30
  # # decay: 0.75
  # # drop_threshold: 0.1
  # decay: 0.9
  # drop_threshold: 0.1
  # warm_up: 30
  # # calibrate_interval: 200
  # calibrate_interval: 200

  # max_attributes: 30
  # max_requests: 60
  # base_window_size: 10
  # generalisation: 1
  # decay: 0.7
  # calibrate_interval: 200

  # max_attributes: 30
  # max_requests: 80
  # base_window_size: 10
  # generalisation: 1
  # decay: 0.8
  # calibrate_interval: 200



  # max_attributes: 30
  # max_requests: 120
  # base_window_size: 20
  # generalisation: 0
  # decay: 0.7
  # calibrate_interval: 200














  # max_attributes: 30
  # max_requests: 50
  # base_window_size: 10
  # generalisation: 1.6
  # decay: 0.7
  # calibrate_interval: 200

  # max_attributes: 30
  # max_requests: 50
  # base_window_size: 10
  # generalisation: 1.6
  # decay: 0.9
  # calibrate_interval: 200

  # max_attributes: 30
  # max_requests: 50
  # base_window_size: 10
  # generalisation: 1.6
  # decay: 0.7
  # calibrate_interval: 200

# __main__: INFO - [1.0, 1.0, 0.6, 0.0]
# __main__: INFO - [0.9956545355784899, 0.7365562194459533, 0.40684410646387836, 0.041825095057034245]

  # max_attributes: 35
  # max_requests: 50
  # base_window_size: 10
  # generalisation: 1.6
  # decay: 0.8
  # calibrate_interval: 200

# __main__: INFO - [1.0, 1.0, 0.6, 0.6, 0.2, 0.0, 0.0, 0.0]
# __main__: INFO - [0.8120586637696904, 0.7479630635524172, 0.41988049972840846, 0.36882129277566544, 0.23302552960347633, 0.1510048886474742, 0.11895708853883757, 0.041825095057034245]

  # max_attributes: 25
  # max_requests: 
  # base_window_size: 500
  # generalisation: 1.6
  # decay: 0.5
  # calibrate_interval: 200


  # max_attributes: 30
  # max_requests: 1000
  # base_window_size: 50
  # generalisation: 1
  # decay: 0.7
  # calibrate_interval: 200

  # max_attributes: 30
  # max_requests: 500
  # base_window_size: 50
  # generalisation: 1.6
  # decay: 0.9
  # calibrate_interval: 200

  # max_attributes: 30
  # max_requests: 500
  # base_window_size: 50
  # generalisation: 1.6
  # decay: 0.8
  # calibrate_interval: 200

  # max_attributes: 30
  # max_requests: 120
  # base_window_size: 40
  # generalisation: 1.6
  # decay: 0.8
  # calibrate_interval: 200

  # max_attributes: 30
  # max_requests: 120
  # base_window_size: 30
  # generalisation: 1.6
  # decay: 0.8
  # calibrate_interval: 200

  # max_attributes: 30
  # max_requests: 120
  # base_window_size: 10
  # generalisation: 1.6
  # decay: 0.9
  # calibrate_interval: 200

  # max_attributes: 30
  # max_requests: 1000
  # base_window_size: 50
  # generalisation: 1.6
  # decay: 0.9
  # calibrate_interval: 200

  # max_attributes: 30
  # max_requests: 1000
  # base_window_size: 30
  # generalisation: 1.6
  # decay: 0.7
  # calibrate_interval: 200

  # max_attributes: 30
  # max_requests: 150
  # base_window_size: 30
  # generalisation: 1.6
  # decay: 0.9
  # calibrate_interval: 200

  # max_attributes: 30
  # max_requests: 500
  # base_window_size: 50
  # generalisation: 1.6
  # decay: 0.9
  # calibrate_interval: 200

  max_attributes: 30
  max_requests: 1000
  base_window_size: 1000
  generalisation: 1.6
  decay: 0.9
  calibrate_interval: 200


